### ISSUE TITLE
Unique number

### ISSUE THREAD

**Issue by kkmax09** [tari-cat/CustomGraffiti#2]
sorry to bother you with this but i have no idea how to get the unique number for the graffiti are you able to tell me how or is there a video for this

**Comment by tari-cat** [comment]
In the description it tells you to set a graffiti combo by inputting a set of unique numbers:
1234 for Medium
12345 for Large
123456 for XL.
These numbers can be in any order and go before the graffiti name in this format:
XXXX_GraffitiName.png

**Comment by kkmax09** [comment]
thank you so much for the clarification
