### ISSUE TITLE
Still not working after following instructions

### ISSUE THREAD

**Issue by XtremerSadiq** [tari-cat/CustomGraffiti#3]
I seemingly did everything correctly and I'm still having issues getting my custom graffiti in the game. I've been informed by someone that you can only use numbers from 1-6, and I feel like that should be specified on the game page. I've only been able to get one piece of graffiti and it was XL with the number code 126453. Is there anything else I'm missing to getting L and M graffiti sizes in?

**Comment by XtremerSadiq** [comment]
> I seemingly did everything correctly and I'm still having issues getting my custom graffiti in the game. I've been informed by someone that you can only use numbers from 1-6, and I feel like that should be specified on the game page. I've only been able to get one piece of graffiti and it was XL with the number code 126453. Is there anything else I'm missing to getting L and M graffiti sizes in?

I think I figured it out actually, you can only have the numbers ranging from the number of characters depending on the size. In other words for medium sizes since there are only 4 points to spray, the numbers for the file can only range from 1-4.

**Comment by tari-cat** [comment]
Yeah, Medium can only use 1234, Large can use 12345, and XL can use 123456, each digit once, in any order, no duplicate digits.

**Comment by XtremerSadiq** [comment]
> Yeah, Medium can only use 1234, Large can use 12345, and XL can use 123456, each digit once, in any order, no duplicate digits.

The mod page says it replaces original combinations, is there a way to know which combinations it replaces?

**Comment by tari-cat** [comment]
It replaces them in a sense of, if you add graffiti with the same combo as graffiti that exists in the base game, it'll overwrite it. If you add multiple with the same combination, it'll randomize between them.
